In [109]:
import numpy as np; import pandas as pd
from typing import Literal, Tuple
import random as rd
from matplotlib import pyplot as plt
import Toolbox_20250801 as toolbox

In [110]:
A = np.matrix(np.random.randint(-100, 100, (4, 3)))
maximinValue_row = toolbox.maximin(A, "row")[0]
worstValue_row = A.min()
print(A, maximinValue_row, worstValue_row, sep = '\n')

[[-62  44  62]
 [-42   4  62]
 [ 24 -77 -68]
 [ 28  80  53]]
28.0
-77


In [111]:
B = np.matrix(np.random.randint(-100, 100, (4, 3)))
maximinValue_col, maximinStrategy_col = toolbox.maximin(B, "column")
print(B, maximinValue_col, maximinStrategy_col.T, sep = '\n')

[[ 13 -33 -63]
 [-76 -90  34]
 [-30 -63 -39]
 [ 85 -33 -24]]
-33.47899159663867
[[0.61344538 0.         0.38655462]]


In [118]:
print(A.tolist())

[[-62, 44, 62], [-42, 4, 62], [24, -77, -68], [28, 80, 53]]


In [119]:
print(B.tolist())

[[13, -33, -63], [-76, -90, 34], [-30, -63, -39], [85, -33, -24]]


In [112]:
riskAversion_row = rd.random()
minimumRequiredValue_row = riskAversion_row*maximinValue_row + (1-riskAversion_row)*worstValue_row
print(riskAversion_row, minimumRequiredValue_row)

0.22016640581967095 -53.88252738893455


In [113]:
strategySpace_row = toolbox.thresholdVertices(A, minimumRequiredValue_row, "row")
print(strategySpace_row)

               Vertex_0  Vertex_1  Vertex_2  Vertex_3  Vertex_4  Vertex_5  \
Probability_0  0.909806  0.905611  0.594126       0.0       0.0  0.000000   
Probability_1  0.000000  0.000000  0.405874       0.0       1.0  0.285401   
Probability_2  0.000000  0.094389  0.000000       0.0       0.0  0.714599   
Probability_3  0.090194  0.000000  0.000000       1.0       0.0  0.000000   

               Vertex_6  Vertex_7  
Probability_0  0.000000  0.191053  
Probability_1  0.000000  0.000000  
Probability_2  0.852755  0.808947  
Probability_3  0.147245  0.000000  


In [114]:
P = np.matrix(strategySpace_row.to_numpy())
print(P)

[[0.90980586 0.90561078 0.59412637 0.         0.         0.
  0.         0.19105349]
 [0.         0.         0.40587363 0.         1.         0.2854009
  0.         0.        ]
 [0.         0.09438922 0.         0.         0.         0.7145991
  0.85275495 0.80894651]
 [0.09019414 0.         0.         1.         0.         0.
  0.14724505 0.        ]]


In [115]:
print(A.shape == B.shape)

True


In [116]:
print(toolbox.Game.fromMatrices(player_1_payoff_matrix = A, player_2_payoff_matrix = B, transposed = True))
print(minimumRequiredValue_row)

            C_0         C_1         C_2
R_0   (-62, 13)   (44, -33)   (62, -63)
R_1  (-42, -76)    (4, -90)    (62, 34)
R_2   (24, -30)  (-77, -63)  (-68, -39)
R_3    (28, 85)   (80, -33)   (53, -24)
-53.88252738893455


In [117]:
enhancedPayoff_col, enhancedStrategy_col = toolbox.maximin(P.T*B, player = "column")
print(enhancedPayoff_col, enhancedStrategy_col.T)
print(maximinValue_col, maximinStrategy_col.T)

-31.734941149827605 [[0.54357914 0.         0.45642086]]
-33.47899159663867 [[0.61344538 0.         0.38655462]]
